import type { Metadata } from 'next';
import Header from '@/containers/Header';
import Nav from '@/containers/Nav';
import Main from '@/containers/Main';
import Footer from '@/containers/Footer';
import StyledComponentsRegistry from '@/components/Ant/AntdRegistry';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  return (
    <html>
      <body>
        <StyledComponentsRegistry>
          <Header />
          <Nav />
          <Main children={children} />
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
